### ISSUE TITLE
Constrain net-http-persistent to < 3.0

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-workflow-service#44]
```
ArgumentError: wrong number of arguments (given 1, expected 0)
/Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:505:in `initialize'
/Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http_persistent.rb:22:in `new'
/Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http_persistent.rb:22:in `net_http_connection'
/Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:33:in `call'
/Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
/Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
/Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/connection.rb:149:in `get'
/Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/dor-workflow-service-2.2.1/lib/dor/services/workflow_service.rb:565:in `send_workflow_resource_request'
/Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/dor-workflow-service-2.2.1/lib/dor/services/workflow_service.rb:554:in `block in workflow_resource_method'
/Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/retries-0.0.5/lib/retries.rb:46:in `with_retries'
/Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/dor-workflow-service-2.2.1/lib/dor/services/workflow_service.rb:551:in `workflow_resource_method'
/Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/dor-workflow-service-2.2.1/lib/dor/services/workflow_service.rb:111:in `get_workflow_xml'
```

2.9.4 is known to work.

**Comment by cbeer** [comment]
I hope faraday will address this with https://github.com/lostisland/faraday/pull/619 soon.
